name: Create and Send ZIP to Discord

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt update && sudo apt install zip -y

    - name: Create ZIP file
      run: zip -r package.py-latest.zip .

    - name: Send ZIP to Discord
      uses: Ilshidur/action-discord@v1
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: |
          **Neues Paket hochgeladen:**
          [package.py](https://github.com/termuxandlinux/package.py)

          Schau dir die neueste Version an!
        file: package.py-latest.zip
